# Generated by Django 4.0.3 on 2022-03-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('posted_on', models.DateField()),
                ('posted_by', models.CharField(max_length=100)),
            ],
        ),
    ]
